title: Jek
email: hello@jek.com
description: >-
  Write an awesome description for your new site here. You can edit this line in
  _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: ''
twitter: tbutler0x90
github: tcbutler320
mail: developer.tbutler@gmail.com
linkedin: tyler-b-a700a1aa
contact: true
about: true
version: v1.1.0
edit-date: false
default-theme: sandcastle
tags: foo bar
developer-controls: false
theme: jek
plugins:
  - jekyll-feed
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: syntax
